import type { Metadata } from "next";
import { ColorSchemeScript, mantineHtmlProps } from "@mantine/core";
import "@mantine/core/styles.css";
import { Geist, Geist_Mono } from "next/font/google";
import PageNavigator from "./components/PageNavigator";
import AppThemeProvider from "./contexts/AppThemeProvider";
import SmoothScroll from "./contexts/SmoothScroll";
import StartupLoader from "./contexts/StartupLoader";
import ThemeToggle from "./contexts/ThemeToggle";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      {...mantineHtmlProps}
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <ColorSchemeScript defaultColorScheme="light" />
      </head>
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <AppThemeProvider>
          <StartupLoader />
          <ThemeToggle />
          <PageNavigator />
          <SmoothScroll>{children}</SmoothScroll>
        </AppThemeProvider>
      </body>
    </html>
  );
}
